### PR TITLE
Fix Image Loading for Podman in E2E Tests

### LINKED ISSUE #407: Improving Podman Compatibility in E2E Test Suite
The llm-d-inference-scheduler e2e tests currently fail when run using Podman.

Hardcoded docker Commands: Despite being able to set CONTAINER_TOOL to “podman” in the Makefile, the run_e2e.sh script, which is executed by the test suite, contains hardcoded docker commands (e.g., docker pull, docker images). This directly breaks the workflow for users who only have Podman installed, as the script fails when it tries to execute a command that doesn't exist. This inconsistency forces Podman users into complex workarounds or prevents them from running the tests altogether. 

Example: https://github.com/llm-d/llm-d-inference-scheduler/blob/main/test/scripts/run_e2e.sh#L14 and https://github.com/llm-d/llm-d-inference-scheduler/blob/main/test/e2e/e2e_suite_test.go#L128 

These issues block developers who primarily use Podman, increase setup friction, and hinder effective local testing and CI alignment.

### PR DESCRIPTION
**Pull request by hdefazio**
Fixes #407 

This pr allows the user to set the CONTAINER_RUNTIME to podman and makes changes needed to the scripts in order to have the e2e tests pass when running with podman
- Uses $CONTAINER_RUNTIME instead of assuming docker 
- Add a more robust check for the check-container-tool make target to catch empty CONTAINER_RUNTIME values
- Renames some environment variables for naming consistency across the scripts
- Separated pulling the images from running the e2e tests into its own script and Make target

Testing:
```
$ make check-container-tool 
✅ Container tool 'podman' found.
```
(this is correct for my system)

Manually set CONTAINER_RUNTIME := "" for testing
```
$ make check-container-tool 
❌ Error: No container tool detected. Please install docker or podman.
make: *** [Makefile:339: check-container-tool] Error 1
```

E2E tests:
```
$ make test-e2e
✅ Container tool 'podman' found.
==== Building Docker image ghcr.io/llm-d/llm-d-inference-scheduler:dev ====
podman build \
        --platform linux/amd64 \
                --build-arg TARGETOS=linux \
        --build-arg TARGETARCH=amd64 \
...
Successfully tagged ghcr.io/llm-d/llm-d-inference-scheduler:dev
a1215c0fcd88a695d054af4ca5f24238b856557ac40bb97daabf850a25291e36
==== Building Sidecar Docker image ghcr.io/llm-d/llm-d-routing-sidecar:dev ====
podman build \
        --build-arg TARGETOS=linux \
        --build-arg TARGETARCH=amd64 \
...
Successfully tagged ghcr.io/llm-d/llm-d-routing-sidecar:dev
2db3ca617335a1a9abfb2a2741b28ed231b0a459d27933d683ec65d0af68523d
==== Pulling Container images ====
./scripts/pull_images.sh
Using container tool: podman
--- Using the following images ---
Scheduler Image:     ghcr.io/llm-d/llm-d-inference-scheduler:dev
Simulator Image:     ghcr.io/llm-d/llm-d-inference-sim:v0.5.0
Sidecar Image:       ghcr.io/llm-d/llm-d-routing-sidecar:dev
----------------------------------------------------
Pulling dependencies...
Checking for image: ghcr.io/llm-d/llm-d-inference-scheduler:dev
 -> Found local image. Proceeding.
Checking for image: ghcr.io/llm-d/llm-d-inference-sim:v0.5.0
 -> Image found on registry. Pulling...
Trying to pull ghcr.io/llm-d/llm-d-inference-sim:v0.5.0...
Getting image source signatures
...
Writing manifest to image destination
9a33dd9554cae425122f55c461e588975d096b9bc259b5ffb41cb08fd29e3dca
    ✅ Successfully pulled image.
Checking for image: ghcr.io/llm-d/llm-d-routing-sidecar:dev
 -> Found local image. Proceeding.
Successfully pulled dependencies
==== Running End to End Tests ====
./test/scripts/run_e2e.sh
Running end to end tests
  "level"=0 "msg"="Successfully loaded environment variable" "key"="CONTAINER_RUNTIME" "value"="podman"
  "level"=0 "msg"="Successfully loaded environment variable" "key"="EPP_TAG" "value"="dev"
  "level"=0 "msg"="Successfully loaded environment variable" "key"="VLLM_SIMULATOR_TAG" "value"="v0.3.0"
  "level"=0 "msg"="Successfully loaded environment variable" "key"="ROUTING_SIDECAR_TAG" "value"="dev"
  "level"=0 "msg"="Environment variable not set, using default value" "key"="READY_TIMEOUT" "defaultValue"="3m0s"
=== RUN   TestEndToEnd
Running Suite: End To End Test Suite - /home/hdefazio/projects/openshift-ai/llm-d-inference-scheduler/test/e2e
==================================================================================================
Random Seed: 1761770233

Will run 3 of 3 specs
------------------------------
[BeforeSuite] 
  enabling experimental podman provider
  Creating cluster "e2e-tests" ...
   • Ensuring node image (kindest/node:v1.34.0) 🖼  ...
   ✓ Ensuring node image (kindest/node:v1.34.0) 🖼
   • Preparing nodes 📦   ...
   ✓ Preparing nodes 📦 
   • Writing configuration 📜  ...
   ✓ Writing configuration 📜
   • Starting control-plane 🕹️  ...
   ✓ Starting control-plane 🕹️
   • Installing CNI 🔌  ...
   ✓ Installing CNI 🔌
   • Installing StorageClass 💾  ...
   ✓ Installing StorageClass 💾
  Set kubectl context to "kind-e2e-tests"
  You can now use your cluster with:

  kubectl cluster-info --context kind-e2e-tests

  Thanks for using kind! 😊
  STEP: Loading ghcr.io/llm-d/llm-d-inference-sim:v0.3.0 into the cluster e2e-tests using podman @ 10/29/25 16:37:33.251
...
  Writing manifest to image destination
  enabling experimental podman provider
  STEP: Loading ghcr.io/llm-d/llm-d-inference-scheduler:dev into the cluster e2e-tests using podman @ 10/29/25 16:37:35.033
...
  Writing manifest to image destination
  enabling experimental podman provider
  STEP: Loading ghcr.io/llm-d/llm-d-routing-sidecar:dev into the cluster e2e-tests using podman @ 10/29/25 16:37:42.495
...
  Writing manifest to image destination
  enabling experimental podman provider
 ...
[BeforeSuite] PASSED [66.291 seconds]
...
[AfterSuite] PASSED [11.440 seconds]
------------------------------
[DeferCleanup (Suite)] PASSED [0.029 seconds]
------------------------------

Ran 3 of 3 Specs in 114.273 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestEndToEnd (114.27s)
PASS
ok      github.com/llm-d/llm-d-inference-scheduler/test/e2e     114.290s
```

### CODE REVIEW

File: scripts/pull_images.sh [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+TARGETOS="${TARGETOS:-$(go env GOOS)}"
+TARGETARCH="${TARGETARCH:-$(go env GOARCH)}"
+
+# --- Helper Function to Ensure Image Availability ---
+# This function checks the registry first, then falls back to a local-only check.
+ensure_image() {
+  local image_name="$1"
+  echo "Checking for image: ${image_name}"
+
+  # Attempt to inspect the image manifest on the remote registry.
```
Comment (shmuelk) [inline scripts/pull_images.sh]: Please check if the image is found locally before looking for it in the remote registry.

File: test/e2e/e2e_suite_test.go [hunk 2]
```diff
@@ -121,12 +121,14 @@ func setupK8sCluster() {
...
 
-	ginkgo.By(fmt.Sprintf("Loading %s into the cluster e2e-tests", image))
+	ginkgo.By(fmt.Sprintf("Loading %s into the cluster e2e-tests using %s", image, container_runtime))
 
-	command := exec.Command("docker", "save", "--platform", "linux/"+runtime.GOARCH,
-		"--output", target, image)
+	_, err := exec.LookPath(container_runtime)
+	gomega.Expect(err).ShouldNot(gomega.HaveOccurred(), "Could not find %s in PATH", container_runtime)
+
+	command := exec.Command(container_runtime, "save", "--output", target, image)
```
Comment (shmuelk) [inline test/e2e/e2e_suite_test.go]: When using Docker as container_runtime, this process fails unless the save was done with the parameter `--platform linux/arm64`

**Comment by shmuelk** [comment]
@hdefazio Please check the lint failure.

File: test/e2e/e2e_suite_test.go (hunk 2 above)
Comment (hdefazio) [reply test/e2e/e2e_suite_test.go]: Got it! I've added it back for docker only

File: scripts/pull_images.sh (hunk 1 above)
Comment (hdefazio) [reply scripts/pull_images.sh]: Updated!

**Review by pierDipi — COMMENTED** [review]
/lgtm

File: Makefile [hunk 3]
```diff
@@ -12,11 +12,15 @@ SIDECAR_NAME ?= pd-sidecar
 IMAGE_REGISTRY ?= ghcr.io/llm-d
 IMAGE_TAG_BASE ?= $(IMAGE_REGISTRY)/$(PROJECT_NAME)
 EPP_TAG ?= dev
+export EPP_TAG
```
Comment (Jooho) [inline Makefile:15]: What is this `export` for? 
if you want to share the same variable between Makefile and script, I recommend you to use env file. like kserve: https://github.com/kserve/kserve/blob/master/kserve-deps.env

Comment (hdefazio) [reply Makefile:15]: I can do that in a follow up pr - I'm trying not to change too much at once for this one to get it merged

Comment (shmuelk) [reply Makefile:15]: Please don't do that. It is much easier to work from the command line that to have to update all sorts of env files. Especially when testing all sorts of permutations of things.

File: Makefile [hunk 4]
```diff
@@ -142,10 +147,10 @@ build-%: check-go install-dependencies download-tokenizer ## Build the project
 .PHONY:	image-build
 image-build: image-build-epp image-build-sidecar ## Build Docker image
 
-.PHONY:	image-build-%
-image-build-%: check-container-tool ## Build Docker image ## Build Docker image using $(CONTAINER_TOOL)
+.PHONY:	%-image-build
+%-image-build: check-container-tool ## Build Docker image ## Build Docker image using $(CONTAINER_RUNTIME)
```
Comment (shmuelk) [inline Makefile]: You accidentally undid an important fix on these lines. 
```suggestion
.PHONY: image-build-%
image-build-%: check-container-tool ## Build Docker image ## Build Docker image using $(CONTAINER_RUNTIME)
```

File: Makefile [hunk 5]
```diff
@@ -154,12 +159,17 @@ image-build-%: check-container-tool ## Build Docker image ## Build Docker image
  		-t $($*_IMAGE) -f Dockerfile.$* .
 
 .PHONY: image-push
-image-push: image-push-epp image-push-sidecar ## Push Docker images to registry
+image-push: epp-image-push sidecar-image-push ## Push container images to registry
```
Comment (shmuelk) [inline Makefile]: You accidentally undid an important fix on this line.
```suggestion
image-push: image-push-epp image-push-sidecar ## Push container images to registry
```

File: Makefile [hunk 6]
```diff
@@ -154,12 +159,17 @@ image-build-%: check-container-tool ## Build Docker image ## Build Docker image
...
 
-.PHONY: image-push-%
-image-push-%: check-container-tool ## Push Docker image to registry
-	@printf "\033[33;1m==== Pushing Docker image $($*_IMAGE) ====\033[0m\n"
-	$(CONTAINER_TOOL) push $($*_IMAGE)
+.PHONY: %-image-push
+%-image-push: check-container-tool load-version-json ## Push container image to registry
```
Comment (shmuelk) [inline Makefile]: You accidentally undid important fixes on these lines.
```suggestion
.PHONY: mage-push-%
image-push-%: check-container-tool ## Push container image to registry
```

File: scripts/pull_images.sh [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+# Set a default VLLM_SIMULATOR_TAG if not provided
+export VLLM_SIMULATOR_TAG="${VLLM_SIMULATOR_TAG:-v0.5.0}"
+# Set the default routing side car image tag
+export SIDECAR_TAG="${SIDECAR_TAG:-dev}"
+
+EPP_IMAGE="ghcr.io/llm-d/llm-d-inference-scheduler:${EPP_TAG}"
+VLLM_SIMULATOR_IMAGE="ghcr.io/llm-d/llm-d-inference-sim:${VLLM_SIMULATOR_TAG}"
+ROUTING_SIDECAR_IMAGE="ghcr.io/llm-d/llm-d-routing-sidecar:${SIDECAR_TAG}"
+
+TARGETOS="${TARGETOS:-$(go env GOOS)}"
```
Comment (shmuelk) [inline scripts/pull_images.sh]: This will not work when running on a Mac.

```suggestion
TARGETOS="${TARGETOS:-linux}"
```

File: test/e2e/e2e_suite_test.go [hunk 8]
```diff
@@ -121,12 +122,21 @@ func setupK8sCluster() {
...
 
-	command := exec.Command("docker", "save", "--platform", "linux/"+runtime.GOARCH,
-		"--output", target, image)
+	_, err := exec.LookPath(containerRuntime)
+	gomega.Expect(err).ShouldNot(gomega.HaveOccurred(), "Could not find %s in PATH", containerRuntime)
+
+	saveArgs := []string{"save", "--output", target}
+	if containerRuntime == "docker" {
+		// The platform flag is required for docker save to work but it is an unsupported flag for podman
+		saveArgs = append(saveArgs, "--platform", fmt.Sprintf("%s/%s", runtime.GOOS, runtime.GOARCH))
```
Comment (shmuelk) [inline test/e2e/e2e_suite_test.go]: This will not work if running the E2E tests on a Mac.
```suggestion
		saveArgs = append(saveArgs, "--platform", fmt.Sprintf("linux/%s", runtime.GOARCH))
```

File: scripts/pull_images.sh [hunk 9]
```diff
@@ -0,0 +1,53 @@
+#!/bin/bash
+
+# Use the CONTAINER_RUNTIME from the environment, or default to docker if it's not set.
+CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"
+echo "Using container tool: ${CONTAINER_RUNTIME}"
+
+# Set a default EPP_TAG if not provided
+export EPP_TAG="${EPP_TAG:-latest}"
```
Comment (shmuelk) [inline scripts/pull_images.sh]: Please default to a tag of dev. Same default as in the Makefile
```suggestion
export EPP_TAG="${EPP_TAG:-dev}"
```

File: Makefile (hunk 3 above)
Comment (hdefazio) [reply Makefile:15]: @shmuelk are you okay with using the export here then?
