### PR TITLE
fix: simplify InferencePool flag to namespace/name format

### LINKED ISSUE #684: Simplify InferencePool CLI flags to use ns/name syntax
Replace `--inference-pool-namespace` and `--inference-pool-name` with single `--inference-pool` flag accepting `namespace/name` format.

This is a review comment from https://github.com/llm-d/llm-d-inference-scheduler/pull/682#discussion_r2894396484

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed #684

### CODE REVIEW

File: cmd/pd-sidecar/main.go [hunk 1]
```diff
@@ -100,16 +99,21 @@ func main() {
...
-			logger.Info("Error: --inference-pool-namespace or INFERENCE_POOL_NAMESPACE environment variable is required when --enable-ssrf-protection is true")
+		if *inferencePool == "" {
+			logger.Info("Error: --inference-pool is required when --enable-ssrf-protection is true")
 			return
 		}
-		if *inferencePoolName == "" {
-			logger.Info("Error: --inference-pool-name or INFERENCE_POOL_NAME environment variable is required when --enable-ssrf-protection is true")
+
+		parts := strings.SplitN(*inferencePool, "/", 2)
+		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
```
Comment (elevran) [inline cmd/pd-sidecar/main.go]: AFAIK, k8s also accepts a single element namespaced name which implies the use of "default" namespace.

**Review by elevran — COMMENTED** [review]
Thanks @gyliu513 - please consider allowing `<name>` (with an implied "default" used for the namespace).

Also, since users might already be using the current flags, we would like to allow for some migration time by deprecating (and not removing) the existing flags. Thus, suggest the following for handling during the deprecation period:
- add deprecation mark on the flags being replaced (might require an update to `pflag` package or manually testing if a deprecated flag was set)
- prefer `--inference-pool` over the name and namespace flags if both are set (and log a message of this)
- if no inference flags are set, use `INFERENCE_POOL` environment or `INFERENCE_POOL_NAMESPACE`/`INFERENCE_POOL_NAME` if these are set.

File: cmd/pd-sidecar/main.go (hunk 1 above)
Comment (gyliu513) [reply cmd/pd-sidecar/main.go]: Done
